#list
a = "I am Ratna Akter Jui.I am student of Faridpur Engineeing college"

# string

In [4]:
a = "I am Ratna Akter Jui.I am student of Faridpur Engineeing college"

In [5]:
# Broke the string
a.split()

['I',
 'am',
 'Ratna',
 'Akter',
 'Jui.I',
 'am',
 'student',
 'of',
 'Faridpur',
 'Engineeing',
 'college']

In [6]:
a_test = a.split()

In [7]:
#print the list
print(a_test)

['I', 'am', 'Ratna', 'Akter', 'Jui.I', 'am', 'student', 'of', 'Faridpur', 'Engineeing', 'college']


# List

In [8]:
Names = ['jui','jewel','Ratna','Akter','Rohan','shikder']

In [9]:
print(Names[0])

jui


In [10]:
#print the index value
print(Names[1])
print(Names[2])
print(Names[3])
print(Names[4])
print(Names[5])

jewel
Ratna
Akter
Rohan
shikder


In [11]:
print(Names)

['jui', 'jewel', 'Ratna', 'Akter', 'Rohan', 'shikder']


In [12]:
#list element in list
'jui' in Names

True

In [13]:
'Japan' in Names

False

In [14]:
#print index value
Names.index('jui')

0

In [15]:
Names.index('jewel')

1

In [16]:
#print index element
Names[3]

'Akter'

In [17]:
Names[2]='Jui'

In [18]:
Names

['jui', 'jewel', 'Jui', 'Akter', 'Rohan', 'shikder']

# tuples

In [19]:

tup1=('Ratna',1,5,'jui','A') #insert tupple
print(tup1)#print tupple

('Ratna', 1, 5, 'jui', 'A')


In [20]:
tup_list=list(tup1) #convert tuple in list
print(tup_list)
tup_list[3]='Jewel' #inset value in definite index
tup_list.append('java') # insert new one element  in list
tup_list.insert(3,'akon')# insert multiple element in list
print(tup_list)

['Ratna', 1, 5, 'jui', 'A']
['Ratna', 1, 5, 'akon', 'Jewel', 'A', 'java']


In [21]:
tup2=tuple(tup_list) #convert list into tuple
print(tup2) #print tuple

('Ratna', 1, 5, 'akon', 'Jewel', 'A', 'java')


In [22]:
tup_list=list(tup1)
tup_list.remove(1) # remove list element
print(tup_list)
del tup_list[3] #delet tuple list element at specified index
tup2=tuple(tup_list)
print(tup2)

['Ratna', 5, 'jui', 'A']
('Ratna', 5, 'jui')


# Array

In [23]:
# numpy Array
import numpy


In [24]:
numpy.array([3,5,8,11]) # diclaration of array

array([ 3,  5,  8, 11])

In [25]:
numpy.ones(5) # print array sequence

array([1., 1., 1., 1., 1.])

In [26]:
numpy.zeros(3) # print array 0 sequence

array([0., 0., 0.])

In [27]:
numpy.arange(6) # print consequtive number in array

array([0, 1, 2, 3, 4, 5])

In [28]:
numpy.arange(6,12) #start and end(not inclusive)

array([ 6,  7,  8,  9, 10, 11])

In [29]:
numpy.arange(6,12,2) # print without upper limit in difference 2

array([ 6,  8, 10])

In [30]:
numpy.linspace(6,12,3) # print with upper limit

array([ 6.,  9., 12.])

In [31]:
numpy.linspace(6,12) # print all the middle value in two range

array([ 6.        ,  6.12244898,  6.24489796,  6.36734694,  6.48979592,
        6.6122449 ,  6.73469388,  6.85714286,  6.97959184,  7.10204082,
        7.2244898 ,  7.34693878,  7.46938776,  7.59183673,  7.71428571,
        7.83673469,  7.95918367,  8.08163265,  8.20408163,  8.32653061,
        8.44897959,  8.57142857,  8.69387755,  8.81632653,  8.93877551,
        9.06122449,  9.18367347,  9.30612245,  9.42857143,  9.55102041,
        9.67346939,  9.79591837,  9.91836735, 10.04081633, 10.16326531,
       10.28571429, 10.40816327, 10.53061224, 10.65306122, 10.7755102 ,
       10.89795918, 11.02040816, 11.14285714, 11.26530612, 11.3877551 ,
       11.51020408, 11.63265306, 11.75510204, 11.87755102, 12.        ])

In [32]:
len(numpy.linspace(6,12)) # print length this two value

50

# Array operation


In [33]:
x_array = numpy.linspace(-1,1,9) # declare a array
print(x_array)

[-1.   -0.75 -0.5  -0.25  0.    0.25  0.5   0.75  1.  ]


In [34]:
y_array = x_array**2 #multiplication of array

In [35]:
print(y_array) #print array

[1.     0.5625 0.25   0.0625 0.     0.0625 0.25   0.5625 1.    ]


In [36]:
z_array =numpy.sqrt(y_array) # square root of array
print(z_array)

[1.   0.75 0.5  0.25 0.   0.25 0.5  0.75 1.  ]


In [37]:
v_array=x_array+y_array #addition of two array
print(v_array)

[ 0.     -0.1875 -0.25   -0.1875  0.      0.3125  0.75    1.3125  2.    ]


In [38]:
v_array=x_array*y_array #multiplication of two array
print(v_array)

[-1.       -0.421875 -0.125    -0.015625  0.        0.015625  0.125
  0.421875  1.      ]


In [39]:
v_array=x_array/y_array # division of two array
print(v_array)

[-1.         -1.33333333 -2.         -4.                 nan  4.
  2.          1.33333333  1.        ]


C:\Users\Ratna Akter\AppData\Local\Temp\ipykernel_13444\1557063016.py:1: RuntimeWarning: invalid value encountered in true_divide
  v_array=x_array/y_array


# Dictionaries

In [40]:
dict={"A":6,"B":"1","C":[3,5,6],"D":(8,4,4),"E":5,"F":9} #define any dictionary
dict

{'A': 6, 'B': '1', 'C': [3, 5, 6], 'D': (8, 4, 4), 'E': 5, 'F': 9}

In [43]:
x = { 'sam': 10, 'ash':[1,2],'man':['asd','dfr']}
x

{'sam': 10, 'ash': [1, 2], 'man': ['asd', 'dfr']}

In [44]:
x['sam'] #print any keyword value

10

In [45]:
x.keys() # print dictionary keywords

dict_keys(['sam', 'ash', 'man'])

In [46]:
x.values() # print dictionary value

dict_values([10, [1, 2], ['asd', 'dfr']])

In [47]:
x['Aziz'] = 2019 #add dictionary value
x

{'sam': 10, 'ash': [1, 2], 'man': ['asd', 'dfr'], 'Aziz': 2019}

In [49]:
del dict['A'] # dectionary delet
dict

{'B': '1', 'C': [3, 5, 6], 'D': (8, 4, 4), 'E': 5, 'F': 9}

In [50]:
'sam' in x

True

In [51]:
'saim' in x # saim is in present dictionary

False

In [52]:
len(x)  #find the length of dictionary

4

In [53]:
# add two dictionary
y ={ 'name':'jui','age':23}
y

{'name': 'jui', 'age': 23}

In [56]:
x.update(y) #update value of y in x
x

{'sam': 10,
 'ash': [1, 2],
 'man': ['asd', 'dfr'],
 'Aziz': 2019,
 'name': 'jui',
 'age': 23}

In [57]:
#clear the dictionry
y.clear()
y

{}

# Set

In [59]:
s1 = set([1,2,3,4,5]) # diclare the set
print(s1)

{1, 2, 3, 4, 5}


In [60]:
s1.add(6) # add a element
print(s1)

{1, 2, 3, 4, 5, 6}


In [62]:
s1.update({7,8,9,10}) # update the value
print(s1)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


In [67]:
s2 =(7,8,9)
s1.update({6,7,8},s2) # update s1 set value with s2 value
print(s1)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


In [69]:
s1.remove(10) # remove set element
print(s1)

{1, 2, 3, 4, 5, 7, 8, 9}


In [71]:
s1.discard(10) # dicard the set value
print(s1)

{1, 2, 3, 4, 5, 7, 8, 9}


In [72]:
s3 =(11,12,13)
s4= s1.intersection(s2) #interset the two set
print(s4)

{8, 9, 7}


In [73]:
s4= s1.difference(s2) #difference between two set values
print(s4)

{1, 2, 3, 4, 5}


In [76]:
s4= s1.symmetric_difference(s2) # symmetric difference value between two set
print(s4)

{1, 2, 3, 4, 5}


In [78]:
s4= s1.difference(s3,s2)
print(s4)

{1, 2, 3, 4, 5}


In [79]:
l1 =[1,2,3,4,1,2,4] #list
l2 = list(set(l1)) # remove repeated value from list by set
print(l2)

[1, 2, 3, 4]


In [80]:
employees =['jui','nanjiba','jenny']
gym_member=['jui','jhumi','sizy']
developers =['jui','sumon','rohan','jenny']

In [85]:
result =set(gym_member).intersection(developers)
print(result)

{'jui'}


In [86]:
result= set(gym_member).difference(developers)
print(result)

{'sizy', 'jhumi'}


# Data frame

In [87]:
import pandas as pa #pandas module


In [89]:
from pandas import DataFrame # called DATAFRAME

In [91]:
education = {'course':['Engineering','Medicine'],'Job':['Engineer','Doctor']} #declare variable

In [92]:
study = DataFrame(education) #create table
study

course       Job
0  Engineering  Engineer
1     Medicine    Doctor

In [94]:
study = DataFrame(education,columns=['Job','course']) #exchange columns
study

Job       course
0  Engineer  Engineering
1    Doctor     Medicine

In [96]:
new_frame=DataFrame(education,columns=['course','Job'],index=['a','b']) #deffine index value
print (new_frame)

        course       Job
a  Engineering  Engineer
b     Medicine    Doctor


In [97]:
new_frame.course #print column

a    Engineering
b       Medicine
Name: course, dtype: object

In [98]:
new_frame.Job

a    Engineer
b      Doctor
Name: Job, dtype: object

In [99]:
new_frame.index.name = 'ID' #define index name

In [101]:
new_frame.columns.name='Education' #define columns name

In [102]:
new_frame

Education       course       Job
ID                              
a          Engineering  Engineer
b             Medicine    Doctor

In [103]:
new_frame['Scope']= new_frame.Job =='Doctor' #define a column for specific raw 
new_frame

Education       course       Job  Scope
ID                                     
a          Engineering  Engineer  False
b             Medicine    Doctor   True